# Generated by Django 4.1.3 on 2022-12-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='title',
        ),
    ]
